### ISSUE TITLE
Adding a custom class prevents the bar showing red in error mode

### ISSUE THREAD

**Issue by cjmyles** [BosNaufal/vue2-loading-bar#6]
I added a custom class to the HTML:

```
<loading-bar
    custom-class="custom-class"
    ...
```

Then set the error mode in the JS:

```
this.error = true;
```

The loading bar appears, but in green not red. Without the custom class there is no issue.

**Comment by BosNaufal** [comment]
Hi @cjmyles, how about custom css?

```css
.CustomClass.LoadingBar--error {
   background: red;
}
```
